### PR TITLE
Removed netstandard1.4 from the library targets

### LINKED ISSUE #175: Add back ...xyzException(SerializationInfo info, StreamingContext context) for 4.5.x and desktop
These constructors should be added back but #ifdef'd for FxCore.

### LINKED ISSUE #1310: Remove dead code from ECDsaAdapter
The following method has no references and appears not to be used anywhere. 

Microsoft.IdentityModel.Tokens.ECDsaAdapter.GetKeySize(string curveId)

I am wondering if it really is dead code and maybe consider removing it or explaining how it used.

### LINKED ISSUE #1321: Remove netstandard1.4 from Wilson 6.x
netstandard1.4 is only supported by netcore1.0, which is not an LTS (long term support) release.

### PR DESCRIPTION
**Pull request by mafurman**
Fixes #1321 - _Remove netstandard1.4 from Wilson 6.x_ 
Fixes #175 - _Add back ...xyzException(SerializationInfo info, StreamingContext context_
Fixes  #1310 - _Remove dead code from ECDsaAdapter_

### CODE REVIEW

File: src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Exceptions/OpenIdConnectProtocolException.cs [hunk 1]
```diff
@@ -26,17 +26,15 @@
...
 {
 
-    #if DESKTOPNET45
-        [Serializable]
-    #endif
-
     /// <summary>
     /// This exception is thrown when an OpenIdConnect protocol handler encounters a protocol error.
     /// </summary>
+    [Serializable]
```
Comment (GeoK) [inline src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Exceptions/OpenIdConnectProtocolException.cs]: w.r.t. Serializable, we need to make sure that the exceptions do serialize properly (tests).
Also, we need to account for additional properties (e.g. SecurityTokenExpiredException has Expires) by overriding GetObjectData #1300 

We should probably add [Serializable] attribute to SignedHttpRequest exceptions (we didn't set it as Serializable didn't work for other assemblies).

File: src/Microsoft.IdentityModel.Tokens/ECDsaAdapter.cs [hunk 2]
```diff
@@ -207,36 +204,6 @@ private uint GetKeyByteCount(string curveId)
             return keyByteCount;
         }
 
-        /// <summary>
```
Comment (GeoK) [inline src/Microsoft.IdentityModel.Tokens/ECDsaAdapter.cs]: Thanks :)

File: src/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey.csproj [hunk 3]
```diff
@@ -9,8 +9,8 @@
     <GenerateDocumentationFile>true</GenerateDocumentationFile>
     <LangVersion>latest</LangVersion>
     <PackageId>Microsoft.IdentityModel.ManagedKeyVaultSecurityKey</PackageId>
-    <TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">net452;netstandard1.4</TargetFrameworks>
-    <TargetFrameworks Condition=" '$(OS)' != 'Windows_NT' ">netstandard1.4</TargetFrameworks>
+    <TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">net452;netstandard2.0</TargetFrameworks>
```
Comment (GeoK) [inline src/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey.csproj]: I don't think that current versions of ManagedKeyVaultSecurityKey dependencies support netstandard2.0.
We should probably upgrade, as the new versions support netstandard2.0.

**Comment by GeoK** [comment]
We should remove netstandard1.4 from buildConfiguration.xml too.

**Comment by mafurman** [comment]
@GeoK Good catch; I'll make sure to remove it from there. I completely forgot we also had it in the buildConfiguration.xml.

**Comment by henrik-me** [comment]
not sure I understand how the serialization change is related to the target change. And why "everywhere" should now be serializable where it wouldn't be before. (removal of DESKTOPNET45 constraint)

**Comment by mafurman** [comment]
@henrik-me The _DESKTOPNET45_ symbol was never defined, so there was actually no target where that code would execute (and so these classes were not serializable regardless of target).

The only target where the SerializableAttribute wasn't available for us was netstandard1.4, which is why we can safely include it now. For reference: https://docs.microsoft.com/en-us/dotnet/api/system.serializableattribute?view=netstandard-2.0

File: src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Exceptions/OpenIdConnectProtocolException.cs (hunk 1 above)
Comment (mafurman) [reply src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Exceptions/OpenIdConnectProtocolException.cs]: I created a separate issue to add `[Serializable]` to `SignedHttpRequest` exceptions: #1324

I've also assigned both #1300 and #1324 to myself; I'll issue separate PRs for both.

File: src/Microsoft.IdentityModel.Tokens/ECDsaAdapter.cs (hunk 2 above)
Comment (mafurman) [reply src/Microsoft.IdentityModel.Tokens/ECDsaAdapter.cs]: :grin:

File: src/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey.csproj (hunk 3 above)
Comment (mafurman) [reply src/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey.csproj]: I've updated the `MicrosoftAzureKeyVaultVersion `to 3.0.5 in dependencies.props and `SystemNetHttpVersion` to 4.3.4 in both dependencies.props and depedenciesTest.props.

It also seems like [`Microsoft.Azure.KeyVault`](https://www.nuget.org/packages/Microsoft.Azure.KeyVault/) has been replaced by a set of different libraries, so it may be worth switching to those as well...

Comment (henrik-me) [reply src/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey.csproj]: I suggest updating all references to the latest available. if not at least to the min recommended version (considering security, performance and feature updates etc.)

File: src/Microsoft.IdentityModel.Tokens/ECDsaAdapter.cs [hunk 4]
```diff
@@ -62,9 +62,6 @@ internal ECDsaAdapter()
                 CreateECDsaFunction = CreateECDsaUsingECParams;
             else
                 CreateECDsaFunction = CreateECDsaUsingCNGKey;
-#elif NETSTANDARD1_4
-            if (SupportsCNGKey())
-                CreateECDsaFunction = CreateECDsaUsingCNGKey;
 #elif DESKTOP
```
Comment (brentschmaltz) [inline src/Microsoft.IdentityModel.Tokens/ECDsaAdapter.cs]: I opened up this issue to address how we deal with DESKTOP
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1325

File: src/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey.csproj (hunk 3 above)
Comment (mafurman) [reply src/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey/Microsoft.IdentityModel.ManagedKeyVaultSecurityKey.csproj]: @henrik-me I'm merging this PR in now, but I created a separate issue to track this: #1326
