### PR TITLE
Fix flaky test

### LINKED ISSUE #2683: [Testing Bug] LifetimeValidationResultTests fails
https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1324067&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=ce91d5d6-0c55-50f5-8ab9-6695c03ab102&l=9050

@iNinja Could you take a look at this failing test. Looks to be one recently added

### PR DESCRIPTION
**Pull request by iNinja**
# Fix flaky test

- [x] You've read the [Contributor Guide](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/Contributing.md) and [Code of Conduct](https://opensource.microsoft.com/codeofconduct/).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] If any gains or losses in performance are possible, you've included benchmarks for your changes. [More info](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Benchmarking-in-Wilson)
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Modified date comparison method in unit tests to fix flaky test.

## Description
Added method to IdentityComparer to compare two dates against an epsilon value to avoid flakiness.

Fixes #2683

### CODE REVIEW

File: test/Microsoft.IdentityModel.TestUtils/IdentityComparer.cs [hunk 1]
```diff
@@ -1669,5 +1669,14 @@ private static string GetString(object str)
             else
                 return string.Format(CultureInfo.InvariantCulture, "{0}", (str ?? "null"));
         }
+
+        public static bool AreDatesEqualWithEpsilon(DateTime? dateTime1, DateTime? dateTime2, int epsilon)
+        {
+            if (dateTime1 is DateTime date1 && dateTime2 is DateTime date2)
```
Comment (keegan-caruso) [inline test/Microsoft.IdentityModel.TestUtils/IdentityComparer.cs:1675]: nit: you can do HasValue instead

**Review by keegan-caruso — APPROVED** [review]

File: test/Microsoft.IdentityModel.TestUtils/IdentityComparer.cs (hunk 1 above)
Comment (iNinja) [reply test/Microsoft.IdentityModel.TestUtils/IdentityComparer.cs:1675]: Would it remove the optionality though? The resulting TimeSpan from substracting two optional DateTimes results in an optional as well, and I cannot call TotalSeconds on it.

File: test/Microsoft.IdentityModel.TestUtils/IdentityComparer.cs [hunk 2]
```diff
@@ -1669,5 +1669,14 @@ private static string GetString(object str)
             else
                 return string.Format(CultureInfo.InvariantCulture, "{0}", (str ?? "null"));
         }
+
+        public static bool AreDatesEqualWithEpsilon(DateTime? dateTime1, DateTime? dateTime2, int epsilon)
```
Comment (msbw2) [inline test/Microsoft.IdentityModel.TestUtils/IdentityComparer.cs:1673]: Shouldn't `epsilon` come from the `CompareContext` instead? Then pass the `CompareContext` here.

File: test/Microsoft.IdentityModel.TestUtils/IdentityComparer.cs (hunk 1 above)
Comment (keegan-caruso) [reply test/Microsoft.IdentityModel.TestUtils/IdentityComparer.cs:1675]: dateTime1 to date1 already remove the optionality doesn't it?

File: test/Microsoft.IdentityModel.TestUtils/IdentityComparer.cs (hunk 2 above)
Comment (brentschmaltz) [reply test/Microsoft.IdentityModel.TestUtils/IdentityComparer.cs:1673]: Why pass nullable?
