### PR TITLE
Switch for metadata refresh to be blocking

### LINKED ISSUE #3192: [Bug] ConfigurationManager.GetConfiguration() no longer performs blocking call, nor throw exception
**Which version of Microsoft.IdentityModel are you using?**
Starting from 8.0.2 until most recent version

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [x] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Is this a new or an existing app?**
Existing application.

**Repro**

```csharp
configurationManager.RequestRefresh();
[...]
configurationManager.GetConfiguration(); // Used to block call until most recent configuration was pulled, or throw exception if it couldn't
```

**Expected behavior**
`GetConfiguration` no longer performs a blocking call when a refresh is required nor does it still throw exceptions when the configuration cannot be reached. (breaking behavior change)

Customers building on top of this behavior may not be aware of it and have (sever) impact on their platforms.

**Actual behavior**
As part of https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2780, the OIDC configuration fetching was moved to a background check which makes `GetConfiguration` no longer a blocking call, nor will it throw exceptions if it cannot pull the configuration anymore.

**Possible solution**
Restore previous behaviour or introduce new approach to be able to block getting configuration in a blocking call.

**Additional context / logs / screenshots / links to code**
Ref internal discussion between identity & Azure API Management

### PR DESCRIPTION
**Pull request by keegan-caruso**
# Switch for metadata refresh to be blocking

- [x] You've read the [Contributor Guide](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/Contributing.md) and [Code of Conduct](https://opensource.microsoft.com/codeofconduct/).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] If any gains or losses in performance are possible, you've included benchmarks for your changes. [More info](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Benchmarking-in-Wilson)
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

Adds the ability for the metadata refresh to be done as a blocking call, as per 8.0.1 behavior.

This is done through the 'Switch.Microsoft.IdentityModel.UpdateConfigAsBlocking'.

If set, configuration calls will be blocking on update, and exceptions when requesting new metadata will be returned to the caller

Fixes #3192

### CODE REVIEW

File: src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager_Blocking.cs [hunk 1]
```diff
@@ -0,0 +1,163 @@
...
+            string updateMode;
+
+            if (_currentConfiguration is null)
+                updateMode = TelemetryConstants.Protocols.FirstRefresh;
+            else
+                updateMode = _refreshRequested ? TelemetryConstants.Protocols.Manual : TelemetryConstants.Protocols.Automatic;
+
+            try
+            {
+                TelemetryClient.IncrementConfigurationRefreshRequestCounter(
```
Comment (GeoK) [inline src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager_Blocking.cs:153]: How would we differentiate between blocking and non-blocking calls in telemetry?

Comment (keegan-caruso) [reply src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager_Blocking.cs:153]: Good question, I read the app context switch in the telemetry client and write that as a tag

**Review by GeoK — DISMISSED** [review]

**Review by jennyf19 — DISMISSED** [review]

File: src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs [hunk 2]
```diff
@@ -149,13 +149,29 @@ public async Task<T> GetConfigurationAsync()
         /// Obtains an updated version of Configuration.
         /// </summary>
         /// <param name="cancel">CancellationToken</param>
-        /// <returns>Configuration of type T.</returns>
-        /// <remarks>If the time since the last call is less than <see cref="BaseConfigurationManager.AutomaticRefreshInterval"/> then <see cref="IConfigurationRetriever{T}.GetConfigurationAsync"/> is not called and the current Configuration is returned.</remarks>
+        /// <returns>Configuration of type <typeparamref name="T"/>.</returns>
+        /// <remarks>
+        /// If the time since the last call is less than <see cref="BaseConfigurationManager.AutomaticRefreshInterval"/>
+        /// then <see cref="IConfigurationRetriever{T}.GetConfigurationAsync"/> is not called and the current Configuration is returned.
+        /// By default, this method blocks until the configuration is retrieved the first time. After the configuration is retrieved,
```
Comment (jmprieur) [inline src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs]: wondering if that would not be a bit clearer?

```suggestion
        /// By default, this method blocks until the configuration is retrieved the first time. After the configuration was retrieved once,
```

File: src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs [hunk 3]
```diff
@@ -149,13 +149,29 @@ public async Task<T> GetConfigurationAsync()
...
+        /// updates will happen in the background. Failures to retrieve the configuration on the background thread will be logged.
+        /// If this operation is configured to be blocking through the switch 'Switch.Microsoft.IdentityModel.UpdateConfigAsBlocking'
+        /// then this method will block when the configuration needs to be updated or hasn't been retrieved. If the configuration
```
Comment (jmprieur) [inline src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs]:
```suggestion
        /// then this method will block each time the configuration needs to be updated or hasn't been retrieved. If the configuration
```

File: src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs [hunk 4]
```diff
@@ -149,13 +149,29 @@ public async Task<T> GetConfigurationAsync()
...
+        /// is unable to be retrieved, an exception will be thrown.
+        /// </remarks>
```
Comment (jmprieur) [inline src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs:172]: Did I capture the trade-off correctly, @keegan-caruso?

```suggestion
        /// By using the app context switch you choose what works best for you when there is a signing key update:
        /// either have validation failures until the new metadata is retrieved (non-blocking behavior), or block all requests
        /// until the new metadata is retrieved and process them at that time. The latest case can lead to thread starvation 
        /// if your service receives a lot of concurrent requests and the signing keys are rotated.
        /// </remarks>
```

File: test/Microsoft.IdentityModel.TestUtils/ResetAppContextSwitchesAttribute.cs [hunk 5]
```diff
@@ -0,0 +1,23 @@
...
+// Licensed under the MIT License.
+
+using System.Reflection;
+using Microsoft.IdentityModel.Tokens;
+using Xunit.Sdk;
+
+namespace Microsoft.IdentityModel.TestUtils
+{
+    /// <inheritdoc/>
+    public class ResetAppContextSwitchesAttribute : BeforeAfterTestAttribute
```
Comment (jmprieur) [inline test/Microsoft.IdentityModel.TestUtils/ResetAppContextSwitchesAttribute.cs:11]: that's very cool

**Review by jmprieur — DISMISSED** [review]

**Review by jennyf19 — APPROVED** [review]

**Review by westin-m — APPROVED** [review]

**Review by pmaytak — APPROVED** [review]
