### PR TITLE
 KeyID should be present in exception messages logs and should not be considered PII.

### LINKED ISSUE #3104: KeyID should be present in exception messages logs and should not be considered PII
Repair item from an incident and the auth client team needed more info, which the exception message did not include but should. KeyID is not PII.

### PR DESCRIPTION
**Pull request by kllysng**
Fixes #3104

### CODE REVIEW

**Review by jmprieur — APPROVED** [review]
LGTM. Thanks @kllysng 
cc: @iNinja FYI

**Review by jmprieur — APPROVED** [review]

**Review by pmaytak — APPROVED** [review]

File: src/Microsoft.IdentityModel.JsonWebTokens/JwtTokenUtilities.cs [hunk 1]
```diff
@@ -367,7 +367,7 @@ private static ValidationError GetDecryptionError(
                 return new ValidationError(
                     new MessageDetail(
                         TokenLogMessages.IDX10603,
-                        keysAttempted.ToString(),
+                        LogHelper.MarkAsNonPII(keysAttempted.ToString()),
```
Comment (keegan-caruso) [inline src/Microsoft.IdentityModel.JsonWebTokens/JwtTokenUtilities.cs:370]: Do we want this to only be the kids?

**Comment by kllysng** [comment]
Updating this PR to include more than just the one log message.

File: src/Microsoft.IdentityModel.Tokens/Validators.cs [hunk 2]
```diff
@@ -365,15 +365,15 @@ internal static void ValidateIssuerSecurityKey(SecurityKey securityKey, Security
             if (validationParameters.IssuerSigningKeyValidatorUsingConfiguration != null)
             {
                 if (!validationParameters.IssuerSigningKeyValidatorUsingConfiguration(securityKey, securityToken, validationParameters, configuration))
-                    throw LogHelper.LogExceptionMessage(new SecurityTokenInvalidSigningKeyException(LogHelper.FormatInvariant(LogMessages.IDX10232, securityKey)) { SigningKey = securityKey });
+                    throw LogHelper.LogExceptionMessage(new SecurityTokenInvalidSigningKeyException(LogHelper.FormatInvariant(LogMessages.IDX10232, LogHelper.MarkAsNonPII(securityKey.ToString()))) { SigningKey = securityKey });
```
Comment (kllysng) [inline src/Microsoft.IdentityModel.Tokens/Validators.cs]: @GeoK double checking that logging the Kid and InternaId is acceptable? [SecurtiyKey.ToString()](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.securitykey.tostring?view=msal-web-dotnet-latest#microsoft-identitymodel-tokens-securitykey-tostring) returns the formatted string: GetType(), KeyId: 'value', InternalId: 'value'.

Comment (kllysng) [reply src/Microsoft.IdentityModel.Tokens/Validators.cs]: Otherwise, I can log Key.Kid + change all the log messages from `.. key: {0}..` to `.. key Kid: {0}..`

Comment (GeoK) [reply src/Microsoft.IdentityModel.Tokens/Validators.cs]: Was the same returned previously? The difference is that now we are not treating it as PII.

Comment (kllysng) [reply src/Microsoft.IdentityModel.Tokens/Validators.cs]: Can confirm that while debugging, logging `SecurityKey` and `SecurityKey.ToString()` both invoke .ToString() and have the same output.

Comment (kllysng) [reply src/Microsoft.IdentityModel.Tokens/Validators.cs]: is it acceptable to also log `InternalId`?

**Review by westin-m — APPROVED** [review]

**Comment by armandRobled** [comment]
Robledo6-patche

Luis Armando Robledo salazar
________________________________

File: src/Microsoft.IdentityModel.Tokens/Validators.cs (hunk 2 above)
Comment (kllysng) [reply src/Microsoft.IdentityModel.Tokens/Validators.cs]: Discussed in internally offline

**Review by westin-m — APPROVED** [review]
