### PR TITLE
Resolve encryption key when Kid is not present in token

### LINKED ISSUE #1431: Token decryption fails if incoming token doesn't have kid (key id) in the protected header.
My application receives encrypted web tokens from AAD. I am using the OWIN middleware for setting up the token decryption parameters. I am setting the `TokenValidationParameters.TokenDecryptionKeys` with a set of two certificates either of which might be used to encrypt the token. (I am testing the certificate rotation flow). 
However, when I am testing the code, I see the following error being reported -

```
Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationMiddleware Error: 0 : Authentication failed
Microsoft.IdentityModel.Tokens.SecurityTokenKeyWrapException: IDX10659: UnwrapKey failed, exception from cryptographic operation: 'System.Security.Cryptography.CryptographicException'
   at Microsoft.IdentityModel.Tokens.RsaKeyWrapProvider.UnwrapKey(Byte[] keyBytes)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.GetContentEncryptionKeys(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.DecryptToken(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.Owin.Security.Jwt.JwtFormat.Unprotect(String protectedText)
```

If I remove the certificate which is currently not being used to encrypt the tokens then the error goes away.

I believe this has to do with the code here - 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/e4928aff114bf17ee04bd0360b15da6d33694b06/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L966

It should not be enclosing the if condition at 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/e4928aff114bf17ee04bd0360b15da6d33694b06/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L981

Looking for suggestions of what is the correct way out here.

Currently to unblock myself, I am adding a token decryption key resolver with the following code - (which is heavily influenced with the code in JsonWebTokenHandler)

```c#
private List<SecurityKey> TokenDecryptionKeyResolver(string token, SecurityToken securityToken, string kid, TokenValidationParameters validationParameters)
{
	using (X509Store store = new X509Store(StoreName.My, StoreLocation.LocalMachine))
	{
			store.Open(OpenFlags.ReadOnly | OpenFlags.OpenExistingOnly);
			X509Certificate2Collection certs = store.Certificates.Find(X509FindType.FindByThumbprint, <thumbprint_new>, true);
			var tokenEncryptionCert = certs[0];			
			certs = store.Certificates.Find(X509FindType.FindByThumbprint, <thumbprint_old>, true);
			var tokenEncryptionCertOld = certs[0];
	}
	List<X509SecurityKey> tokenDecryptionKeys = new List<X509SecurityKey> {
																	new X509SecurityKey(tokenEncryptionCert),
																	new X509SecurityKey(tokenEncryptionCertOld) };
	if (!string.IsNullOrEmpty(kid))
	{
			foreach (var key in tokenDecryptionKeys)
			{
					if (key != null && string.Equals(key.KeyId, kid, StringComparison.OrdinalIgnoreCase))
					{
							return new List<SecurityKey>() { key };
					}
			}
	}
	if (securityToken is JwtSecurityToken)
	{
			JwtSecurityToken jwtToken = securityToken as JwtSecurityToken;
			if (!string.IsNullOrEmpty(jwtToken?.Header.X5t))
			{
					foreach (var key in tokenDecryptionKeys)
					{
							if (string.Equals(key.X5t, jwtToken.Header.X5t, StringComparison.OrdinalIgnoreCase))
							{
									return new List<SecurityKey>() { key };
							}
					}
			}
	}
	return null;
}
```

### PR DESCRIPTION
**Pull request by RojaEnnam**
Fixes #1431 in both `JsonWebTokenHandler `and `JwtSecurityTokenHandler`.

- Modify current logic to also resolve encryption keys when security token does not contain key identifier.
- Add try catch in `GetContentEncryptionKeys` to catch exception and continue with other keys
- Add unit tests to test new behavior.

### CODE REVIEW

File: src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs [hunk 1]
```diff
@@ -965,7 +979,7 @@ protected virtual SecurityKey ResolveTokenDecryptionKey(string token, JsonWebTok
 
             if (!string.IsNullOrEmpty(jwtToken.Kid))
             {
-                if (validationParameters.TokenDecryptionKey != null
+                 if (validationParameters.TokenDecryptionKey != null
```
Comment (keegan-caruso) [inline src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs]: nit: bonus whitespace?

File: test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs [hunk 2]
```diff
@@ -303,6 +303,97 @@ public static TheoryData<CreateTokenTheoryData> CreateJWETheoryData
...
+
+                IdentityComparer.AreEqual(encryptionKeysFromJsonHandlerWithKid, encryptionKeysFromJsonHandlerWithNoKid, context);
+                theoryData.ExpectedException.ProcessNoException(context);
+            }
+            catch (Exception ex)
+            {
+                theoryData.ExpectedException.ProcessException(ex.InnerException, context);
+            }
+            TestUtilities.AssertFailIfErrors(context);
+        }
```
Comment (keegan-caruso) [inline test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs:334]: nit: usually have a new line between a brace and a method

File: src/Microsoft.IdentityModel.JsonWebTokens/GlobalSuppressions.cs [hunk 3]
```diff
@@ -20,3 +20,4 @@
...
 [assembly: SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "Has no fields or properties", Scope = "type", Target = "~T:Microsoft.IdentityModel.JsonWebTokens.JwtHeaderParameterNames")]
 [assembly: SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "Has no fields or properties", Scope = "type", Target = "~T:Microsoft.IdentityModel.JsonWebTokens.JwtRegisteredClaimNames")]
+[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Exception is wrote to string", Scope = "member", Target = "~M:Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.GetContentEncryptionKeys(Microsoft.IdentityModel.JsonWebTokens.JsonWebToken,Microsoft.IdentityModel.Tokens.TokenValidationParameters)~System.Collections.Generic.IEnumerable{Microsoft.IdentityModel.Tokens.SecurityKey}")]
```
Comment (mafurman) [inline src/Microsoft.IdentityModel.JsonWebTokens/GlobalSuppressions.cs]: nit: I believe the proper grammar here is "exception is written to a string"

File: src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs (hunk 1 above)
Comment (RojaEnnam) [reply src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs]: Yes, removed it.

File: test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs [hunk 4]
```diff
@@ -2360,6 +2361,99 @@ public static TheoryData<ParametersCheckTheoryData> ParametersCheckTheoryData()
...
             };
         }
+
+        [Theory, MemberData(nameof(SecurityTokenDecryptionTheoryData))]
+        public void GetEncryptionKeys(CreateTokenTheoryData theoryData)
+        {
+            var context = TestUtilities.WriteHeader($"{this}.EncryptionKeysCheck", theoryData);
+            try
+            {
+                TestUtilities.AssertFailIfErrors(context);
```
Comment (GeoK) [inline test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs]: Why do we need this line here?

File: test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs [hunk 5]
```diff
@@ -303,6 +303,98 @@ public static TheoryData<CreateTokenTheoryData> CreateJWETheoryData
...
 
+        [Theory, MemberData(nameof(SecurityTokenDecryptionTheoryData))]
+        public void GetEncryptionKeys(CreateTokenTheoryData theoryData)
+        {
+            var context = TestUtilities.WriteHeader($"{this}.EncryptionKeysCheck", theoryData);
+            try
+            {
+                string jweFromJsonHandlerWithKid = theoryData.JsonWebTokenHandler.CreateToken(theoryData.Payload, theoryData.TokenDescriptor.SigningCredentials, theoryData.TokenDescriptor.EncryptingCredentials);
+                var jwtTokenFromJsonHandlerWithKid = new JsonWebToken(jweFromJsonHandlerWithKid);
+                var getContentEncryptionKeysMethod = theoryData.JsonWebTokenHandler.GetType().GetMethod("GetContentEncryptionKeys", BindingFlags.Instance | BindingFlags.NonPublic);
```
Comment (GeoK) [inline test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerTests.cs]: Consider making GetContentEncryptionKeys internal to eliminate reflection from tests, and refactor the code to test if decryption keys for a given token and set of parameters matches an expected set of keys.

File: src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs [hunk 6]
```diff
@@ -934,17 +934,31 @@ private IEnumerable<SecurityKey> GetContentEncryptionKeys(JsonWebToken jwtToken,
...
+                        var kwp = key.CryptoProviderFactory.CreateKeyWrapProviderForUnwrap(key, jwtToken.Alg);
+                        var unwrappedKey = kwp.UnwrapKey(Base64UrlEncoder.DecodeBytes(jwtToken.EncryptedKey));
+                        unwrappedKeys.Add(new SymmetricSecurityKey(unwrappedKey));
+                    }
                 }
+                catch (Exception ex)
+                {
+                    exceptionStrings.AppendLine(ex.ToString());
+                }
+                keysAttempted.AppendLine(key.ToString() + " , KeyId: " + key.KeyId);
```
Comment (GeoK) [inline src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs]: Not sure if we need the keyId here, as SecurityKey.ToString() prints it too:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/19092cb44fd556084c4cef9dfef08ec38e2ee130/src/Microsoft.IdentityModel.Tokens/SecurityKey.cs#L92-L95

File: src/Microsoft.IdentityModel.Tokens/LogMessages.cs [hunk 7]
```diff
@@ -119,7 +119,7 @@ internal static class LogMessages
         public const string IDX10610 = "IDX10610: Decryption failed. Could not create decryption provider. Key: '{0}', Algorithm: '{1}'.";
         public const string IDX10611 = "IDX10611: Decryption failed. Encryption is not supported for: Algorithm: '{0}', SecurityKey: '{1}'.";
         public const string IDX10612 = "IDX10612: Decryption failed. Header.Enc is null or empty, it must be specified.";
-        // public const string IDX10613 = "IDX10613:";
+        public const string IDX10613 = "IDX10613: Key unwrap failed using decryption Keys: '{0}'.\nExceptions caught:\n '{1}'.\ntoken: '{2}'.";
```
Comment (GeoK) [inline src/Microsoft.IdentityModel.Tokens/LogMessages.cs]: You should use a new log id for this message. Log Id is considered deprecated if it's commented out. We are using this approach to make sure not to re-use a log id as it might lead to some confusion.

File: test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs (hunk 4 above)
Comment (RojaEnnam) [reply test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs]: We don't need it. I think I forgot to delete it. I removed it now.

File: src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs (hunk 6 above)
Comment (RojaEnnam) [reply src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs]: You're right, we don't need KeyId. I made the change.

File: src/Microsoft.IdentityModel.Tokens/LogMessages.cs (hunk 7 above)
Comment (RojaEnnam) [reply src/Microsoft.IdentityModel.Tokens/LogMessages.cs]: That answers why they were commented out :) Thank you. I added a new message ID.

**Review by GeoK — APPROVED** [review]
