### PR TITLE
Xiao/better exception for get OIDC configuration async

### LINKED ISSUE #1714: [FeatureRequest] Better Transient/ClientMisconfiguration error handling for ConfigurationManager.GetConfigurationAsync?
During token validation, our service uses the below `ConfigurationManager.GetConfigurationAsync` API in order to retrieve the `OpenIdConnectConfiguration` for a tenant-specific authority (e.g.: `https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/`):
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/4f24eaecffca2a0ebacc63976682df0adab54805/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L124

For this particular API, our service would like to distinguish between two types of errors:
- **Transient Errors:** If the underlying `HttpDocumentRetriever` fails to call `https://login.windows.net/{tenantId}/.well-known/openid-configuration` due to some transient I/O or networking issue, then we want to surface this to the customer as a `503 ServiceUnavailable` error. This signals to the customer that the issue is transient, so that they can configure a retry policy to try again later.	
- **ClientMisconfiguration Errors:** Sometimes, customers will accidentally use a tenant ID belonging to the wrong environment (e.g.: the Microsoft PPE tenant `f686d426-8d16-42db-81b7-ab578e110ccd` doesn't exist in the Public Azure environment `https://login.windows.net`). When the underlying `HttpDocumentRetriever` calls `https://login.windows.net/f686d426-8d16-42db-81b7-ab578e110ccd/.well-known/openid-configuration`, it gets back a `400 BadRequest` error (`AADSTS90002: Tenant 'f686d426-8d16-42db-81b7-ab578e110ccd' not found.`). We want to surface this to the customer as a `401 Unauthorized` error with some appropriate error code (e.g.: `InvalidTenant`).

Currently, our service is unable to distinguish between the above two classes of errors. In both scenarios, the underlying ConfigurationManager/HttpDocumentRetriever throws an `InvalidOperationException` with an `IDX208xx`-level error code. **Could the error handling for this API be improved so that we can distinguish between these two types of errors?** It would be great if the thrown exception could surface additional data, such as the following:
- **HTTP status code** (e.g.: `400 BadRequest` or `500 InternalServerError`).
- **Error message** (assuming that PII can be sanitized without making the error message useless).
- **Correlation ID** (for the scenario where our DevOps engineers need to escalate a legitimate outage and provide eSTS/AAD a correlation ID for some incident).

**Internal tracking**
- [Product Backlog Item 1601972](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1601972 ): Better error handling for MetadataManager.GetOidcConfigurationAsync
  - [Product Backlog Item 1509137](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1509137): Create new exception type that contains errors from ESTS and add as InnerException to AuthenticationException

### PR DESCRIPTION
**Pull request by ciaozhang**
Modify wilson to include http status code and response string in exception.Data dictionary so that SAL can parse the response from exception.Data and populate properties on the new exception.

### CODE REVIEW

File: src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs [hunk 1]
```diff
@@ -44,6 +44,11 @@ public class HttpDocumentRetriever : IDocumentRetriever
         private HttpClient _httpClient;
         private static readonly HttpClient _defaultHttpClient = new HttpClient();
 
+#pragma warning disable 1591
```
Comment (mafurman) [inline src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs]: What warning is this disabling?

File: src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs [hunk 2]
```diff
@@ -120,7 +125,9 @@ public async Task<string> GetDocumentAsync(string address, CancellationToken can
                 if (response.IsSuccessStatusCode)
                     return responseContent;
 
-                 unsuccessfulHttpResponseException = new IOException(LogHelper.FormatInvariant(LogMessages.IDX20807, address, response, responseContent));
+                unsuccessfulHttpResponseException = new IOException(LogHelper.FormatInvariant(LogMessages.IDX20807, address, response, responseContent));
```
Comment (mafurman) [inline src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs:133]: Should we create a different exception name for this? If we did, we could have StatusCode and ResponseContent as properties on it.

Not sure if we'd consider changing the exception type a breaking change though.

File: test/Microsoft.IdentityModel.Protocols.Tests/HttpDocumentRetrieverTests.cs [hunk 3]
```diff
@@ -91,6 +92,12 @@ public void GetMetadataTest(DocumentRetrieverTheoryData theoryData)
             {
                 aex.Handle((x) =>
                 {
+                    if (x.Data.Count > 0)
+                    {
+                        Assert.True(x.Data.Contains(HttpDocumentRetriever.StatusCode));
```
Comment (mafurman) [inline test/Microsoft.IdentityModel.Protocols.Tests/HttpDocumentRetrieverTests.cs]: We generally try to use CompareContext.AddDiff() rather than relying on Asserts, as Assert failures will cause the test to terminate and will not notify us of failures further on in the test.

**Review by mafurman — CHANGES_REQUESTED** [review]

File: src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs (hunk 1 above)
Comment (ciaozhang) [reply src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs]: Missing XML comment for publicly visible type or member 'Type_or_Member'

File: src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs (hunk 2 above)
Comment (ciaozhang) [reply src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs:133]: I  create a new exception(GetOidcConfigurationException) in SAL and it has StatusCode and ResponseContent as properties there

File: src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs (hunk 1 above)
Comment (TimHannMSFT) [reply src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs]: Why not populate the XML comment?

File: test/Microsoft.IdentityModel.Protocols.Tests/HttpDocumentRetrieverTests.cs (hunk 3 above)
Comment (ciaozhang) [reply test/Microsoft.IdentityModel.Protocols.Tests/HttpDocumentRetrieverTests.cs]: use context.adddiff in latest commit

File: src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs (hunk 1 above)
Comment (ciaozhang) [reply src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs]: added XML

File: src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs (hunk 2 above)
Comment (mafurman) [reply src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs:133]: Would it make more sense for Wilson to throw that exception directly? Is there anything in it that is first party only?

**Review by mafurman — APPROVED** [review]

File: src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs (hunk 2 above)
Comment (ciaozhang) [reply src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs:133]: George has mentioned in teams channel, it might not the best solution to parse the response from AAD in Wilson since Wilson is IDP-agnostic.
